name: Clang Format Checker
on: [pull_request]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "inc/*.h,src/*.c"
          file: ".clang-format"
